CircleApp/ViewModels/Friends/FriendshipVM.cs
using CircleApp.Data.Models;

namespace CircleApp.ViewModels.Friends
{
    public class FriendshipVM
    {
        public List<FriendRequest> FriendRequestsSent = new List<FriendRequest>();
        public List<FriendRequest> FriendRequestsReceived = new List<FriendRequest>();
        public List<Friendship> Friends = new List<Friendship>();
    }
}

CircleApp/ViewModels/Friends/UserWithFriendsCountVM.cs
namespace CircleApp.ViewModels.Friends
{
    public class UserWithFriendsCountVM
    {
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string? ProfilePictureUrl { get; set; }
        public int FriendsCount { get; set; }
        public string FriendsCountDisplay => FriendsCount == 0 ? "No followers" : FriendsCount == 1 ? "1 follower" : $"{FriendsCount} followers";
    }
}

CircleApp/Controllers/FriendsController.cs
using CircleApp.Controllers.Base;
using CircleApp.Data.Helpers.Constants;
using CircleApp.Data.Services;
using CircleApp.ViewModels.Friends;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CircleApp.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class FriendsController : BaseController
    {
        private readonly IFriendsService _friendsService;
        private readonly INotificationsService _notificationsService;

        public FriendsController(IFriendsService friendsService, INotificationsService notificationsService)
        {
            _friendsService = friendsService;
            _notificationsService = notificationsService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();

            if (!userId.HasValue)
                RedirectToLogin();

            var friendsData = new FriendshipVM()
            {
                FriendRequestsSent = await _friendsService.GetSentFriendRequestAsync(userId.Value),
                FriendRequestsReceived = await _friendsService.GetReceivedFriendRequestAsync(userId.Value),
                Friends = await _friendsService.GetFriendsAsync(userId.Value),
            };

            return View(friendsData);
        }

        [HttpPost]
        public async Task<IActionResult> SendFriendRequest(int receiverId)
        {
            var userId = GetUserId();
            var userName = GetUserFullName();

            if (!userId.HasValue) 
                RedirectToLogin();

            await _friendsService.SendRequestAsync(userId.Value, receiverId);
            await _notificationsService.AddNewNotificationAsync(receiverId, NotificationType.FriendRequest, userName, null);

            return RedirectToAction("Index","Home");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFriendRequest(int requestId, string status)
        {
            var userId = GetUserId();
            var userName = GetUserFullName();

            if (!userId.HasValue)
                RedirectToLogin(); 

            var request = await _friendsService.UpdateRequestAsync(requestId, status);

            if (status == FriendshipStatus.Accepted)
            {
                await _notificationsService.AddNewNotificationAsync(request.SenderId, NotificationType.FriendRequestApproved, userName, null);
            }
               

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFriend(int friendshipId)
        {
            await _friendsService.RemoveFriendAsync(friendshipId);
            return RedirectToAction("Index");
        }
    }
}

CircleApp/Controllers/UsersController.cs
using CircleApp.Controllers.Base;
using CircleApp.Data.Helpers.Constants;
using CircleApp.Data.Models;
using CircleApp.Data.Services;
using CircleApp.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CircleApp.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class UsersController : BaseController
    {
        private readonly IUsersService _usersService;
        private readonly UserManager<User> _userManager;
        public UsersController(IUsersService usersService, UserManager<User> userManager)
        {
            _usersService = usersService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(int userId)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            var userPosts = await _usersService.GetUserPosts(userId);
            var userProfile = new GetUserProfileVM()
            {
                User = user,
                Posts = userPosts
            };

            return View(userProfile);
        }
    }
}

CircleApp/Views/Friends/Index.cshtml
@using System.Security.Claims
@model FriendshipVM

<main id="site__main" class="2xl:ml-[--w-side] xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">
    <div class="2xl:max-w-[1220px] max-w-[1065px] mx-auto">
        @if (Model.Friends.Count > 0)
        {
            <div class="sm:my-6 my-3 flex items-center justify-between">
                <div>
                    <h2 class="text-lg text-base font-semibold text-black">My Friends</h2>
                    <p class="font-normal text-sm text-gray-500 leading-6">Your personal network of friends and acquaintances. Connect, share, and stay in touch with people who matters to you.</p>
                </div>
            </div>

            <div class="grid grid-cols-2 gap-2">
                @foreach (var _friendship in Model.Friends)
                {
                    var friend = _friendship.SenderId == int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier)) ?
                    _friendship.Receiver :
                    _friendship.Sender;

                    <div class="flex md:items-center space-x-4 p-4 rounded-md box">

                        <div class="w-14 h-14 flex-shrink-0 rounded-lg relative">
                            <img src="@(string.IsNullOrEmpty(friend.ProfilePictureUrl) ? Url.Content("~/images/avatar/user.png") : friend.ProfilePictureUrl)"
                                 class="absolute w-full h-full inset-0 rounded-md object-cover shadow-sm" />
                        </div>

                        <div class="flex-1">
                            <a asp-controller="Users" asp-action="Details" asp-route-userId="@friend.Id" class="text-base font-semibold capitalize text-black">@friend.FullName</a>
                        </div>

                        <form asp-controller="Friends" asp-action="RemoveFriend" method="post">
                            <input type="hidden" name="friendshipId" value="@_friendship.Id" />
                            <button type="submit" class="button bg-red-soft text-red gap-1 max-md:hidden">
                                <ion-icon name="remove-circle-outline" class="text-xl -ml-1"></ion-icon> Remove
                            </button>
                        </form>
                    </div>
                }
            </div>
        }


        @if (Model.FriendRequestsReceived.Count > 0)
        {
            <div class="sm:my-6 my-3 flex items-center justify-between">
                <div>
                    <h2 class="text-lg text-base font-semibold text-black">Received Requests</h2>
                    <p class="font-normal text-sm text-gray-500 leading-6">See who wants to connect with you! Review and respond to incoming friend requests to expand your circle..</p>
                </div>
            </div>

            <div class="grid grid-cols-2 gap-2">
                @foreach (var request in Model.FriendRequestsReceived)
                {
                    <div class="flex md:items-center space-x-4 p-4 rounded-lg box">
                        <div class="w-14 h-14 flex-shrink-0 rounded-lg relative">
                            <img class="absolute w-full h-full inset-0 rounded-md object-cover shadow-sm" src="@(string.IsNullOrEmpty(request.Sender.ProfilePictureUrl) ? Url.Content("~/images/avatars/user.png") : request.Sender.ProfilePictureUrl)" />
                        </div>
                        <div class="flex-1">
                            <a asp-controller="Users" asp-action="Details" asp-route-userId="@request.Sender.Id" class="text-base font-semibold capitalize text-black">@request.Sender.FullName</a>
                        </div>
                        <form asp-controller="Friends" asp-action="UpdateFriendRequest">
                            <input type="hidden" name="requestId" value="@request.Id" />
                            <input type="hidden" name="status" value="@FriendshipStatus.Rejected" />
                            <button type="submit" class="button bg-red-soft text-red gap-1 max-md:hidden">
                                <ion-icon name="remove-circle-outline" class="text-xl -ml-1"></ion-icon>Reject
                            </button>
                        </form>
                        <form asp-controller="Friends" asp-action="UpdateFriendRequest">
                            <input type="hidden" name="requestId" value="@request.Id" />
                            <input type="hidden" name="status" value="@FriendshipStatus.Accepted" />
                            <button type="submit" class="button bg-primary-soft text-primary gap-1 max-md:hidden">
                                <ion-icon name="checkbox-outline" class="text-xl -ml-1"></ion-icon>Accept
                            </button>
                        </form>
                    </div>
                }
            </div>
        }

        @if (Model.FriendRequestsSent.Count > 0)
        {
            <div class="sm:my-6 my-3 flex items-center justify-between">
                <div>
                    <h2 class="text-lg text-base font-semibold text-black">Pending Invitations</h2>
                    <p class="font-normal text-sm text-gray-500 leading-6">Track friends requests you've sent. See who hasn't responded yet and manage your pending invitations.</p>
                </div>
            </div>

            <div class="grid grid-cols-2 gap-2">
                @foreach (var request in Model.FriendRequestsSent)
                {
                    <div class="flex md:items-center space-x-4 p-4 rounded-lg box">
                        <div class="w-14 h-14 flex-shrink-0 rounded-lg relative">
                            <img class="absolute w-full h-full inset-0 rounded-md object-cover shadow-sm" src="@(string.IsNullOrEmpty(request.Receiver.ProfilePictureUrl) ? Url.Content("~/images/avatars/user.png") : request.Receiver.ProfilePictureUrl)" />
                        </div>
                        <div class="flex-1">
                            <a asp-controller="Users" asp-action="Details" asp-route-userId="@request.Receiver.Id" class="text-base font-semibold capitalize text-black">@request.Receiver.FullName</a>
                        </div>
                        <form asp-controller="Friends" asp-action="UpdateFriendRequest">
                            <input type="hidden" name="requestId" value="@request.Id" />
                            <input type="hidden" name="status" value="@FriendshipStatus.Canceled" />
                            <button type="submit" class="button text-primary gap-1 max-md:hidden">
                                <ion-icon name="remove-circle-outline" class="text-xl -ml-1"></ion-icon>Cancel
                            </button>
                        </form>
                    </div>
                }
            </div>
        }
    </div>
</main>