CircleApp/Controllers/FavoritesController.cs
using CircleApp.Data.Helpers.Constants;
using CircleApp.Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CircleApp.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class FavoritesController : Controller
    {
        private readonly IPostService _postService;
        public FavoritesController(IPostService postService) 
        {
            _postService = postService;
        }
        public async Task<IActionResult> Index()
        {
            var loggedInUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var myFavoritePosts = await _postService.GetAllFavoritedPostsAsync(int.Parse(loggedInUser));
            return View(myFavoritePosts);
        }
    }
}

CircleApp/Controllers/FriendsController.cs
using CircleApp.Controllers.Base;
using CircleApp.Data.Helpers.Constants;
using CircleApp.Data.Services;
using CircleApp.ViewModels.Friends;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CircleApp.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class FriendsController : BaseController
    {
        private readonly IFriendsService _friendsService;
        private readonly INotificationsService _notificationsService;

        public FriendsController(IFriendsService friendsService, INotificationsService notificationsService)
        {
            _friendsService = friendsService;
            _notificationsService = notificationsService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();

            if (!userId.HasValue)
                RedirectToLogin();

            var friendsData = new FriendshipVM()
            {
                FriendRequestsSent = await _friendsService.GetSentFriendRequestAsync(userId.Value),
                FriendRequestsReceived = await _friendsService.GetReceivedFriendRequestAsync(userId.Value),
                Friends = await _friendsService.GetFriendsAsync(userId.Value),
            };

            return View(friendsData);
        }

        [HttpPost]
        public async Task<IActionResult> SendFriendRequest(int receiverId)
        {
            var userId = GetUserId();
            var userName = GetUserFullName();

            if (!userId.HasValue) 
                RedirectToLogin();

            await _friendsService.SendRequestAsync(userId.Value, receiverId);
            await _notificationsService.AddNewNotificationAsync(receiverId, NotificationType.FriendRequest, userName, null);

            return RedirectToAction("Index","Home");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFriendRequest(int requestId, string status)
        {
            var userId = GetUserId();
            var userName = GetUserFullName();

            if (!userId.HasValue)
                RedirectToLogin(); 

            var request = await _friendsService.UpdateRequestAsync(requestId, status);

            if (status == FriendshipStatus.Accepted)
            {
                await _notificationsService.AddNewNotificationAsync(request.SenderId, NotificationType.FriendRequestApproved, userName, null);
            }
               

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFriend(int friendshipId)
        {
            await _friendsService.RemoveFriendAsync(friendshipId);
            return RedirectToAction("Index");
        }
    }
}

CircleApp/Controllers/SettingsController.cs
using CircleApp.Controllers.Base;
using CircleApp.Data.Helpers.Constants;
using CircleApp.Data.Helpers.Enums;
using CircleApp.Data.Models;
using CircleApp.Data.Services;
using CircleApp.ViewModels.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CircleApp.Controllers
{
    [Authorize(Roles = $"{AppRoles.User}, {AppRoles.Admin}")]
    public class SettingsController : BaseController
    {
        private readonly IUsersService _usersService;
        private readonly IFilesService _filesService;
        private readonly UserManager<User> _userManager;
        public SettingsController(IUsersService usersService, IFilesService filesService, UserManager<User> userManager)
        {
            _usersService = usersService;
            _filesService = filesService;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var loggedInUserId = await _userManager.GetUserAsync(User);
            return View(loggedInUserId);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfilePicture(UpdateProfilePictureVM profilePictureVM)
        {
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null)
                return RedirectToLogin();

            var uploadedProfilePictureUrl = await _filesService.UploadImageAsync(profilePictureVM.ProfilePictureImage, ImageFileType.ProfilePicture);
            await _usersService.UpdateUserProfilePicture(loggedInUserId.Value, uploadedProfilePictureUrl);
            return RedirectToAction("Index");
        }
    }
}

CircleApp/Views/Shared/Navigation/_SideBar.cshtml
<div id="site__sidebar" class="fixed top-0 left-0 z-[99] pt-[--m-top] overflow-hidden transition-transform xl:duration-500 max-xl:-translate-x-full">
    <div class="p-2 max-xl:bg-white shadow-sm 2xl:w-72 sm:w-64 w-[80%] h-[calc(100vh-64px)] relative z-30 max-lg:border-r dark:max-xl:!bg-slate-700 dark:border-slate-700">
        <div class="pr-4" data-simplebar>
            <nav id="side">
                <ul>
                    <li>
                        <a asp-controller="Home" asp-action="Index">
                            <img src="~/images/icons/home.png" class="w-6" /><span>Feed</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Favorites" asp-action="Index">
                            <img src="~/images/icons/page.png" class="w-6" /><span>Favorites</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Friends" asp-action="Index">
                            <img src="~/images/icons/group-2.png" class="w-6" /><span>Friends</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <nav id="side" class="font-medium text-sm text-black border-t pt-3 mt-2">
                <div class="pt-3 pb-2 text-sm font-medium">
                    <div class="text-black">Pages</div>
                </div>
                <ul class="mt-2 -space-y-2">
                    <li>
                        <a asp-controller="Settings" asp-action="Index">
                            <svg width="800px" height="800px" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" stroke-width="3" stroke="#000000" fill="none"><path d="M45,14.67l-2.76,2a1,1,0,0,1-1,.11L37.65,15.3a1,1,0,0,1-.61-.76l-.66-3.77a1,1,0,0,0-1-.84H30.52a1,1,0,0,0-1,.77l-.93,3.72a1,1,0,0,1-.53.65l-3.3,1.66a1,1,0,0,1-1-.08l-3-2.13a1,1,0,0,0-1.31.12l-3.65,3.74a1,1,0,0,0-.13,1.26l1.87,2.88a1,1,0,0,1,.1.89L16.34,27a1,1,0,0,1-.68.63l-3.85,1.06a1,1,0,0,0-.74,1v4.74a1,1,0,0,0,.8,1l3.9.8a1,1,0,0,1,.72.57l1.42,3.15a1,1,0,0,1-.05.92l-2.13,3.63a1,1,0,0,0,.17,1.24L19.32,49a1,1,0,0,0,1.29.09L23.49,47a1,1,0,0,1,1-.1l3.74,1.67a1,1,0,0,1,.59.75l.66,3.79a1,1,0,0,0,1,.84h4.89a1,1,0,0,0,1-.86l.58-4a1,1,0,0,1,.58-.77l3.58-1.62a1,1,0,0,1,1,.09l3.14,2.12a1,1,0,0,0,1.3-.15L50,45.06a1,1,0,0,0,.09-1.27l-2.08-3a1,1,0,0,1-.09-1l1.48-3.43a1,1,0,0,1,.71-.59L53.77,35a1,1,0,0,0,.8-1V29.42a1,1,0,0,0-.8-1l-3.72-.78a1,1,0,0,1-.73-.62l-1.45-3.65a1,1,0,0,1,.11-.94l2.15-3.14A1,1,0,0,0,50,18l-3.71-3.25A1,1,0,0,0,45,14.67Z" /><circle cx="32.82" cy="31.94" r="9.94" /></svg>
                            <span>Settings</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div id="site__sidebar__overly" class="absolute top-0 left-0 z-20 w-screen h-screen xl:hidden backdrop-blur-sm" uk-toggle="target: #site__sidebar ; cls :!-translate-x-0">
    </div>
</div>

CircleApp/Views/Shared/Navigation/_TopBar.cshtml
@inject UserManager<User> UserManager
@{
    var loggedInUser = await UserManager.GetUserAsync(User);
    var userName = loggedInUser?.UserName;
    var fullName = loggedInUser?.FullName;
    var profilePictureUrl = loggedInUser?.ProfilePictureUrl;
}
<header class="z-[100] h-[--m-top] fixed top-0 left-0 w-full flex items-center bg-white/80 bg-sky-50 backdrop-blur-xl border-b border-slate-200">
    <div class="2xl:w-[--w-side] lg:w-[--w-side-sm]">
        @* section: Burger icon and App logo *@
        <div class="flex items-center gap-1">
            <button uk-toggle="target: #site__sidebar ; cls :!-translate-x-0" class="flex items-center justify-center w-8 h-8 text-xl rounded-full hover\:bg-gray-100 xl:hidden group">
                <ion-icon name="menu-outline" class="text-2xl group-aria-expanded:hidden"></ion-icon>
                <ion-icon name="close-outline" class="hidden text-2xl group-aria-expanded:block"></ion-icon>
            </button>
            <div id="logo" class="flex items-center">
                <a asp-controller="Home" asp-action="Index" class="flex items-center">
                    <img src="~/images/logo.png" class="w-10 ml-2 md:block hidden" />
                    <span class="ml-2">Circle App</span>
                </a>
            </div>
        </div>
    </div>
    <div class="flex-1 relative">
        <div class="max-w-[1220px] mx-auto flex items-center">
            @* Search *@
            <form id="search--box" class="xl:w-[680px] sm:w-96 sm:relative rounded-xl overflow-hidden z-20 bg-secondary max-md:hidden w-screen left-0 max-sm:top-2">
                <ion-icon name="search" class="absolute left-4 top-1/2 -translate-y-1/2"></ion-icon>
                <input type="text" name="query" placeholder="Search Posts, Friends..." class="w-full !pl-10 font-normal bg-gray-100 h-12 !text-sm" />
            </form>
        </div>
        <div class="max-w-[1220px] mx-auto flex items-center">
            <div class="flex items-center gap-sm-4 gap-2 absolute right-5 top-1/2 -translate-y-1/2 text-black">
                @* Notification *@
                <button type="button" class="p-sm-2 p-1 rounded-full relative sm:bg-secondery" id="notificationBtn">
                    <svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m5.705 3.71-1.41-1.42C1 5.563 1 7.935 1 11h1l1-.063C3 8.009 3 6.396 5.705 3.71zm13.999-1.42-1.408 1.42C21 6.396 21 8.009 21 11l2-.063c0-3.002 0-5.374-3.296-8.647zM12 22a2.98 2.98 0 0 0 2.818-2H9.182A2.98 2.98 0 0 0 12 22zm7-7.414V10c0-3.217-2.185-5.927-5.145-6.742C13.562 2.52 12.846 2 12 2s-1.562.52-1.855 1.258C7.184 4.073 5 6.783 5 10v4.586l-1.707 1.707A.996.996 0 0 0 3 17v1a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-1a.996.996 0 0 0-.293-.707L19 14.586z" /></svg>
                    <div class="absolute top-0 right-0 -m-1 bg-red-600 text-white text-xs px-1 rounded-full" id="notificationCount">0</div>
                </button>
                <div class="hidden bg-white pr-1.5 rounded-lg drop-shadow-xl md:w-[365px] w-screen border2" uk-drop="offset:6;pos: bottom-right; mode: click; animate-out: true;">
                    <div class="flex items-center justify-between gap-2 p-4 pb-2">
                        <h3 class="font-bold text-xl">Notifications</h3>
                    </div>
                    <div class="text-sm h-[400px] w-full overflow-y-auto pr-2">
                        <div class="pl-2 p-1 text-sm font-normal" id="notification-dropdown">No notifications...</div>
                    </div>
                </div>
                @* Profile icon *@
                <div class="rounded-full relative bg-secondary cursor-pointer shrink-0">
                    <img src="@(string.IsNullOrEmpty(profilePictureUrl) ? Url.Content("~/images/avatars/user.png") : profilePictureUrl)" class="sm:w-9 sm:h-9 w-7 h-7 rounded-full shadow shrink-0" />
                </div>
                <div class="hidden bg-white rounded-lg drop-shadow-xl w-64 border2" uk-drop="offset:6;pos: bottom-right; animate-out: true; ">
                    <a>
                        <div class="p-4 py-5 flex items-center gap-4">
                            <img src="@(string.IsNullOrEmpty(profilePictureUrl) ? Url.Content("~/images/avatars/user.png") : profilePictureUrl)" class="w-10 h-10 rounded-full shadow" />
                            <div class="flex-1">
                                <h4 class="text-sm font-medium text-black">@fullName</h4>
                                <div class="text-sm mt-1 text-blue-600 font-light/70">@userName</div>
                            </div>
                        </div>
                    </a>
                    <hr />
                    <nav>
                        <a asp-controller="Settings" asp-action="Index">
                            <div class="flex items-center gap-2.5 hover:bg-secondary p-2 px-2.5 rounded-md">
                                <ion-icon name="settings-outline" class="text-lg"></ion-icon>
                                My Account
                            </div>
                        </a>
                        <hr />
                        <a asp-controller="Authentication" asp-action="Logout">
                            <div class="flex items-center gap-2.5 hover:bg-secondary p-2 px-2.5 rounded-md">
                                <ion-icon name="exit-outline" class="text-lg"></ion-icon>
                                Log Out
                            </div>
                        </a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aspnet-signalr/1.0.27/signalr.min.js" 
integrity="sha512-a+73ErrZPjhqOu0qbW1QLsenEF4pvDjmnd+Ws6hkDyJlrwAigOQAxQhIT+fPNFWScUvtJQvn+G535TT2C6/G4g==" 
crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        
        fetch("Notifications/GetCount",{
            method: 'GET',
            headers: {
                'Content-Type':'application/json'
            }
        }).then(response => response.json()).then(data => {
            console.log("notifications count = ", data);
            document.getElementById("notificationCount").innerHTML = data;
        }).catch(error => {
            console.error("Error fetching notification count: ", error);
        })

        document.getElementById('notificationBtn').addEventListener('click', () => {
            fetch('Notifications/GetNotifications').then(resp => resp.text()).then(html => {
                document.getElementById('notification-dropdown').innerHTML = html;
            })
        });

        //SignalR connection
        const connection = new signalR.HubConnectionBuilder().withUrl("/notificationHub").build();

        connection.on("RecieveNotification", (message) => {
            console.log("message ==>", message)
            document.getElementById("notificationCount").innerHTML = message;
        });

        connection.start().then(() => console.log("SignalR connected")).catch((err) => console.log("SignalR connection error: ", err))
    });

    function setNotificationAsRead(notificationId){
            console.log('Mark as read => notification => ', notificationId);

            fetch(`Notifications/SetNotificationAsRead?notificationId=${notificationId}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                }
                }).then(resp => resp.text()).then(html => {
                document.getElementById('notification-dropdown').innerHTML = html;
            })
        }
</script>

CircleApp/Views/Shared/Navigation/_TopBarAdmin.cshtml
@inject UserManager<User> UserManager
@{
    var loggedInUser = await UserManager.GetUserAsync(User);
    var userName = loggedInUser?.UserName;
    var fullName = loggedInUser?.FullName;
    var profilePictureUrl = loggedInUser?.ProfilePictureUrl;
}
<header class="z-[100] h-[--m-top] fixed top-0 left-0 w-full flex items-center bg-white/80 bg-sky-50 backdrop-blur-xl border-b border-slate-200">
    <div class="2xl:w-[--w-side] lg:w-[--w-side-sm]">
        @* section: Burger icon and App logo *@
        <div class="flex items-center gap-1">
            <button uk-toggle="target: #site__sidebar ; cls :!-translate-x-0" class="flex items-center justify-center w-8 h-8 text-xl rounded-full hover\:bg-gray-100 xl:hidden group">
                <ion-icon name="menu-outline" class="text-2xl group-aria-expanded:hidden"></ion-icon>
                <ion-icon name="close-outline" class="hidden text-2xl group-aria-expanded:block"></ion-icon>
            </button>
            <div id="logo" class="flex items-center">
                <a asp-controller="Home" asp-action="Index" class="flex items-center">
                    <img src="~/images/logo.png" class="w-10 ml-2 md:block hidden" />
                    <span class="ml-2">Circle App - Admin</span>
                </a>
            </div>
        </div>
    </div>
    <div class="flex-1 relative">
        
        <div class="max-w-[1220px] mx-auto flex items-center">
            <div class="flex items-center gap-sm-4 gap-2 absolute right-5 top-1/2 -translate-y-1/2 text-black">

                @* Profile icon *@
                <div class="rounded-full relative bg-secondary cursor-pointer shrink-0">
                    <img src="@(string.IsNullOrEmpty(profilePictureUrl) ? Url.Content("~/images/avatars/user.png") : profilePictureUrl)" class="sm:w-9 sm:h-9 w-7 h-7 rounded-full shadow shrink-0" />
                </div>

                <div class="hidden bg-white rounded-lg drop-shadow-xl w-64 border2" uk-drop="offset:6;pos: bottom-right; animate-out: true; ">
                    <a>
                        <div class="p-4 py-5 flex items-center gap-4">
                            <img src="@(string.IsNullOrEmpty(profilePictureUrl) ? Url.Content("~/images/avatars/user.png") : profilePictureUrl)" class="w-10 h-10 rounded-full shadow" />
                            <div class="flex-1">
                                <h4 class="text-sm font-medium text-black">@fullName</h4>
                                <div class="text-sm mt-1 text-blue-600 font-light/70">@userName</div>
                            </div>
                        </div>
                    </a>
                    <hr />
                    <nav>
                        <a asp-controller="Settings" asp-action="Index">
                            <div class="flex items-center gap-2.5 hover:bg-secondary p-2 px-2.5 rounded-md">
                                <ion-icon name="settings-outline" class="text-lg"></ion-icon>
                                My Account
                            </div>
                        </a>
                        <hr />
                        <a asp-controller="Authentication" asp-action="Logout">
                            <div class="flex items-center gap-2.5 hover:bg-secondary p-2 px-2.5 rounded-md">
                                <ion-icon name="exit-outline" class="text-lg"></ion-icon>
                                Log Out
                            </div>
                        </a>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</header>