CircleApp/Controllers/FavoritesController.cs
using CircleApp.Data.Helpers.Constants;
using CircleApp.Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CircleApp.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class FavoritesController : Controller
    {
        private readonly IPostService _postService;
        public FavoritesController(IPostService postService) 
        {
            _postService = postService;
        }
        public async Task<IActionResult> Index()
        {
            var loggedInUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var myFavoritePosts = await _postService.GetAllFavoritedPostsAsync(int.Parse(loggedInUser));
            return View(myFavoritePosts);
        }
    }
}

CircleApp/ViewComponents/HashtagsViewComponent.cs
using CircleApp.Controllers;
using CircleApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CircleApp.ViewComponents
{
    public class HashtagsViewComponent : ViewComponent 
    {
        private readonly AppDbContext _context;

        public HashtagsViewComponent(AppDbContext contect)
        {
            _context = contect;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var top3Hashtags = await _context.Hashtags.Where(h => h.DateCreated >= h.DateCreated.AddDays(-7)).OrderByDescending(n => n.Count).Take(3).ToListAsync();
            return View(top3Hashtags);
        }
    }
}

CircleApp/ViewComponents/StoriesViewComponent.cs
using CircleApp.Data;
using CircleApp.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CircleApp.ViewComponents
{
    public class StoriesViewComponent : ViewComponent
    {
        private readonly IStoriesServices _storiesService;

        public StoriesViewComponent(IStoriesServices storiesService)
        {
            _storiesService = storiesService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var allStories = await _storiesService.GetAllStoriesAsync();
            return View(allStories);
        }
    }
}

CircleApp/ViewComponents/SuggestedFriendsViewComponent.cs
using CircleApp.Data.Services;
using CircleApp.ViewModels.Friends;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CircleApp.ViewComponents
{
    public class SuggestedFriendsViewComponent : ViewComponent
    {
        private readonly IFriendsService _friendsService;

        public SuggestedFriendsViewComponent(IFriendsService friendsService)
        {
            _friendsService = friendsService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var loggedInUserId = ((ClaimsPrincipal)User).FindFirstValue(ClaimTypes.NameIdentifier);
            var suggestedFriends = await _friendsService.GetSuggestedFriendsAsync(int.Parse(loggedInUserId));
            var suggestedFriendsVM = suggestedFriends.Select(n => new UserWithFriendsCountVM()
            {
                UserId = n.User.Id,
                FullName = n.User.FullName,
                ProfilePictureUrl = n.User.ProfilePictureUrl,
                FriendsCount = n.FriendsCount
            }).ToList();
            return View(suggestedFriendsVM);
        }
    }
}

CircleApp/Views/Favorites/Index.cshtml
@model List<Post>

<main id="site__main" class="2xl:ml-[--w-side] xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">
    <div class="lg:flex 2xl:gap-16 gap-12 max-w-[1065px] mx-auto" id="js-oversized">
        <div class="max-w-[680px] mx-auto">
            @* Story placeholder *@
            @* @await Component.InvokeAsync("Stories") *@
            
            <div class="md:max-w-[580px] mx-auto flex-1 xl:space-y-6 space-y-3">
                
                
                @if (Model.Count == 0)
                {
                    <div class="bg-white rounded-xl shadow-smmd:p-4 p-2 space-y-4 text-sm font-mediumborder1" style="width:580px;">
                        Currently, there are no favorited posts available.
                    </div>
                }
                else
                {
                    @foreach (var post in Model)
                    {
                        <partial name="Home/_Post" model="post" view-data='new ViewDataDictionary(ViewData){{"ShowAllComments", false}}' />
                    }
                }
               
            </div>

        </div>

        <div class="flex-1">
            <div class="lg:space-y-4 lg:pb-8 max-lg:grid sm:grid-cols-2 max-lg:gap-6">
                @await Component.InvokeAsync("SuggestedFriends")
            </div>
            <div class="box p-5 px-6 border1">
                @await Component.InvokeAsync("Hashtags")
            </div>
        </div>
    </div>
</main>
<partial name="Modals/_CreateStory" model="new StoryVM()" />
<partial name="Modals/_CreateStatus" model="new PostVM()" />
<partial name="Home/_PostDeleteConfirmation" />

<script>
    function openPostDeleteConfirmation(postId) {
        UIkit.dropdown('.post-options-dropdown').hide();
        document.getElementById('deleteConfirmationPostId').value = postId;
        UIkit.modal('#postDeleteDialog').show();
    }
</script>